// <auto-generated />
using System;
using FinancialDataTracker.DataAccess.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialDataTracker.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429133247_mig04_StockDetailsNullable")]
    partial class mig04_StockDetailsNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("WatchlistStock", b =>
                {
                    b.Property<Guid>("StocksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WatchlistsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StocksId", "WatchlistsId");

                    b.HasIndex("WatchlistsId");

                    b.ToTable("WatchlistStock");
                });

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.Stock", b =>
                {
                    b.OwnsOne("FinancialDataTracker.Entities.Concrete.StockDetails", "StockDetails", b1 =>
                        {
                            b1.Property<Guid>("StockId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Currency")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.Property<string>("DisplaySymbol")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DisplaySymbol");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Symbol");

                            b1.Property<string>("Type")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Type");

                            b1.HasKey("StockId");

                            b1.HasIndex("Symbol")
                                .IsUnique();

                            b1.ToTable("Stocks");

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("StockDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("WatchlistStock", b =>
                {
                    b.HasOne("FinancialDataTracker.Entities.Concrete.Stock", null)
                        .WithMany()
                        .HasForeignKey("StocksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialDataTracker.Entities.Concrete.Watchlist", null)
                        .WithMany()
                        .HasForeignKey("WatchlistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
