// <auto-generated />
using System;
using FinancialDataTracker.DataAccess.Concrete.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinancialDataTracker.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429150806_mig04_AddQuoteSnapshot")]
    partial class mig04_AddQuoteSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.StockQuoteSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "FetchedAtUtc");

                    b.HasIndex("Symbol", "FetchedAtUtc");

                    b.ToTable("StockQuoteSnapshots");
                });

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Watchlists");
                });

            modelBuilder.Entity("WatchlistStock", b =>
                {
                    b.Property<Guid>("StocksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WatchlistsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StocksId", "WatchlistsId");

                    b.HasIndex("WatchlistsId");

                    b.ToTable("WatchlistStock");
                });

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.Stock", b =>
                {
                    b.OwnsOne("FinancialDataTracker.Entities.Concrete.StockDetails", "StockDetails", b1 =>
                        {
                            b1.Property<Guid>("StockId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Currency")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Currency");

                            b1.Property<string>("Description")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.Property<string>("DisplaySymbol")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DisplaySymbol");

                            b1.Property<string>("Symbol")
                                .IsRequired()
                                .HasColumnType("nvarchar(450)")
                                .HasColumnName("Symbol");

                            b1.Property<string>("Type")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Type");

                            b1.HasKey("StockId");

                            b1.HasIndex("Symbol")
                                .IsUnique();

                            b1.ToTable("Stocks");

                            b1.WithOwner()
                                .HasForeignKey("StockId");
                        });

                    b.Navigation("StockDetails")
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.StockQuoteSnapshot", b =>
                {
                    b.HasOne("FinancialDataTracker.Entities.Concrete.Stock", "Stock")
                        .WithMany("QuoteSnapshots")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FinancialDataTracker.Entities.Concrete.StockQuote", "Quote", b1 =>
                        {
                            b1.Property<Guid>("StockQuoteSnapshotId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Change")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("CurrentPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<DateTime?>("FinnhubTimestampUtc")
                                .HasColumnType("datetime2");

                            b1.Property<decimal>("HighPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("LowPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("OpenPrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("PercentChange")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.Property<decimal>("PreviousClosePrice")
                                .HasPrecision(18, 4)
                                .HasColumnType("decimal(18,4)");

                            b1.HasKey("StockQuoteSnapshotId");

                            b1.ToTable("StockQuoteSnapshots");

                            b1.WithOwner()
                                .HasForeignKey("StockQuoteSnapshotId");
                        });

                    b.Navigation("Quote")
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("WatchlistStock", b =>
                {
                    b.HasOne("FinancialDataTracker.Entities.Concrete.Stock", null)
                        .WithMany()
                        .HasForeignKey("StocksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancialDataTracker.Entities.Concrete.Watchlist", null)
                        .WithMany()
                        .HasForeignKey("WatchlistsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinancialDataTracker.Entities.Concrete.Stock", b =>
                {
                    b.Navigation("QuoteSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
